# mkdir -p ~/.config/sops/age

# Generate a user key from ssh key
# nix shell nixpkgs#ssh-to-age --command bash -c "ssh-to-age -private-key -i ~/.ssh/id_ed25519 > ~/.config/sops/age/keys.txt"

# Generate a user key
# nix shell nixpkgs#age --command bash -c "age-keygen -o ~/.config/sops/age/keys.txt"

# Display the user public key:
# nix shell nixpkgs#age --command bash -c "age-keygen -y ~/.config/sops/age/keys.txt"

# sudo mkdir -p /var/lib/private/sops/age

# Make a host key:
# sudo nix shell nixpkgs#age --command bash -c "age-keygen -o /var/lib/private/sops/age/keys.txt"

# Display the host public key:
# sudo nix shell nixpkgs#age --command bash -c "age-keygen -y /var/lib/private/sops/age/keys.txt"

# Add secrets
# nix shell nixpkgs#sops --command bash -c "SOPS_AGE_KEY_FILE=~/.config/sops/age/keys.txt sops secrets/secrets.yaml"

# Rekey secrets.yaml after editing recipients in .sops.yaml:
# nix shell nixpkgs#sops --command bash -c "SOPS_AGE_KEY_FILE=~/.config/sops/age/keys.txt sops updatekeys secrets/secrets.yaml"
keys:
  - &user_dmyaskovskiy age1snsdjmckv9z4xuvl5eatp5repcsk9zn66sf2nn3xcguwdt46vczsm5fuwv
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *user_dmyaskovskiy
